/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abscorp;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;



/**
 *
 * @author muzammil
 */
public class Supervisor extends javax.swing.JFrame {
    
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    JFileChooser saveFileChooser;

    /**
     * Creates new form Supervisor
     */
    public Supervisor() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        label_username.setText((Employee.username).toString());
        
        conn = db.java_db();
        /////////////////////
        
        fillCombo();
        hideAll();
        
        saveFileChooser = new JFileChooser();
        saveFileChooser.setFileFilter(new FileNameExtensionFilter("TXT files", "txt"));
        
    }
    
    
    
    
    private void fillCombo(){
    try{
        String sql = "SELECT * FROM employee WHERE supervisor = ?";
        pst = conn.prepareStatement(sql);
        pst.setString(1,Employee.username);
        rs = pst.executeQuery();
        
        while(rs.next()){
            String emp = rs.getString(1) +" , "+ rs.getString(6);
            sup_combo.addItem(emp);
            
            String empID = rs.getString(1);
            sup_empID.setText(empID);
            
            String salary = rs.getString(4);
            sup_salary.setText(salary);
            
            String firstName = rs.getString(6);
            sup_firstName.setText(firstName);
            
            String lastName = rs.getString(7);
            sup_lastName.setText(lastName);
            
            String age = rs.getString(8);
            sup_age.setText(age);
            
            String dob = rs.getString(10);
            sup_dob.setText(dob);
            
            String email = rs.getString(11);
            sup_email.setText(email);
            
            String contact = rs.getString(12);
            sup_contact.setText(contact);
            
            String status = rs.getString(13);
            sup_status.setText(status);
            
            
        }
    
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error from linking combo box with database");
        JOptionPane.showMessageDialog(null,e);
        
    }
    
    
    
    
    }
    private void hideAll(){
    
        try{
            
           
            empID.setVisible(false);
            firstName.setVisible(false);
            lastName.setVisible(false);
            age.setVisible(false);
            dob.setVisible(false);
            email.setVisible(false);
            contact.setVisible(false);
            sup_status.setVisible(false);
            salary.setVisible(false);
            
            sup_firstName.setVisible(false);
            sup_empID.setVisible(false);
            sup_lastName.setVisible(false);
            sup_age.setVisible(false);
            sup_dob.setVisible(false);
            sup_contact.setVisible(false);
            sup_email.setVisible(false);
            sup_salary.setVisible(false);
            sup_delete.setVisible(false);
            
            btn_save.setVisible(false);
            txt_area.setVisible(false);
            ver_scrl.setVisible(false);
             
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error from hiding");
            JOptionPane.showMessageDialog(null,e);
        }
    
    
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_username = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        sup_combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        empID = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        salary = new javax.swing.JLabel();
        sup_empID = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        sup_status = new javax.swing.JLabel();
        sup_firstName = new javax.swing.JLabel();
        sup_lastName = new javax.swing.JLabel();
        sup_age = new javax.swing.JLabel();
        sup_dob = new javax.swing.JLabel();
        sup_salary = new javax.swing.JLabel();
        sup_contact = new javax.swing.JLabel();
        sup_email = new javax.swing.JLabel();
        sup_delete = new javax.swing.JButton();
        sup_writeFile = new javax.swing.JButton();
        sup_show = new javax.swing.JButton();
        ver_scrl = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        btn_save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        label_username.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        label_username.setForeground(new java.awt.Color(164, 254, 128));
        label_username.setText("username");
        jPanel1.add(label_username);
        label_username.setBounds(130, 550, 150, 50);

        jLabel2.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(164, 254, 128));
        jLabel2.setText("Logged as  :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 550, 110, 50);

        btn_logout.setFont(new java.awt.Font("Andika", 0, 18)); // NOI18N
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abscorp/images/powee.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout);
        btn_logout.setBounds(760, 20, 140, 50);

        sup_combo.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        sup_combo.setForeground(new java.awt.Color(106, 1, 95));
        sup_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sup_comboActionPerformed(evt);
            }
        });
        jPanel1.add(sup_combo);
        sup_combo.setBounds(50, 370, 190, 40);

        jLabel3.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Track Associate Details :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 320, 210, 50);

        empID.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        empID.setForeground(new java.awt.Color(217, 255, 0));
        empID.setText("Employee ID");
        jPanel1.add(empID);
        empID.setBounds(210, 30, 150, 40);

        firstName.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        firstName.setForeground(new java.awt.Color(217, 255, 0));
        firstName.setText("First Name");
        jPanel1.add(firstName);
        firstName.setBounds(210, 70, 130, 30);

        salary.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        salary.setForeground(new java.awt.Color(217, 255, 0));
        salary.setText("Basic Salary");
        jPanel1.add(salary);
        salary.setBounds(210, 260, 120, 46);

        sup_empID.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        sup_empID.setForeground(new java.awt.Color(252, 224, 224));
        sup_empID.setText("123");
        jPanel1.add(sup_empID);
        sup_empID.setBounds(370, 30, 150, 40);

        age.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        age.setForeground(new java.awt.Color(217, 255, 0));
        age.setText("Age");
        jPanel1.add(age);
        age.setBounds(210, 130, 110, 50);

        contact.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        contact.setForeground(new java.awt.Color(217, 255, 0));
        contact.setText("Contact");
        jPanel1.add(contact);
        contact.setBounds(210, 230, 110, 50);

        email.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(217, 255, 0));
        email.setText("E-mail");
        jPanel1.add(email);
        email.setBounds(210, 200, 130, 50);

        dob.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        dob.setForeground(new java.awt.Color(217, 255, 0));
        dob.setText("DOB");
        jPanel1.add(dob);
        dob.setBounds(210, 170, 100, 40);

        lastName.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        lastName.setForeground(new java.awt.Color(217, 255, 0));
        lastName.setText("Last Name");
        jPanel1.add(lastName);
        lastName.setBounds(210, 100, 130, 40);

        sup_status.setFont(new java.awt.Font("Noto Sans Mono", 1, 24)); // NOI18N
        sup_status.setForeground(new java.awt.Color(171, 24, 188));
        sup_status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abscorp/images/sphere.png"))); // NOI18N
        sup_status.setText(" Active");
        jPanel1.add(sup_status);
        sup_status.setBounds(530, 20, 180, 40);

        sup_firstName.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        sup_firstName.setForeground(new java.awt.Color(252, 224, 224));
        sup_firstName.setText("Muzammil");
        jPanel1.add(sup_firstName);
        sup_firstName.setBounds(370, 60, 190, 40);

        sup_lastName.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        sup_lastName.setForeground(new java.awt.Color(252, 224, 224));
        sup_lastName.setText("Thottathil");
        jPanel1.add(sup_lastName);
        sup_lastName.setBounds(370, 90, 210, 50);

        sup_age.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        sup_age.setForeground(new java.awt.Color(252, 224, 224));
        sup_age.setText("21");
        jPanel1.add(sup_age);
        sup_age.setBounds(370, 130, 90, 40);

        sup_dob.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        sup_dob.setForeground(new java.awt.Color(252, 224, 224));
        sup_dob.setText("13/10/1998");
        jPanel1.add(sup_dob);
        sup_dob.setBounds(370, 160, 150, 40);

        sup_salary.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        sup_salary.setForeground(new java.awt.Color(252, 224, 224));
        sup_salary.setText("50000");
        jPanel1.add(sup_salary);
        sup_salary.setBounds(370, 260, 120, 40);

        sup_contact.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        sup_contact.setForeground(new java.awt.Color(252, 224, 224));
        sup_contact.setText("9746404624");
        jPanel1.add(sup_contact);
        sup_contact.setBounds(370, 230, 140, 40);

        sup_email.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        sup_email.setForeground(new java.awt.Color(252, 224, 224));
        sup_email.setText("muzammilthottathil@cet.ac.in");
        jPanel1.add(sup_email);
        sup_email.setBounds(370, 200, 380, 40);

        sup_delete.setBackground(new java.awt.Color(79, 240, 170));
        sup_delete.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        sup_delete.setForeground(new java.awt.Color(1, 31, 106));
        sup_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abscorp/images/cr.png"))); // NOI18N
        sup_delete.setText("Delete");
        sup_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sup_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(sup_delete);
        sup_delete.setBounds(530, 70, 130, 50);

        sup_writeFile.setBackground(new java.awt.Color(79, 240, 170));
        sup_writeFile.setFont(new java.awt.Font("Andika", 1, 14)); // NOI18N
        sup_writeFile.setForeground(new java.awt.Color(1, 31, 106));
        sup_writeFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abscorp/images/txt.png"))); // NOI18N
        sup_writeFile.setText("Write a File");
        sup_writeFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sup_writeFileActionPerformed(evt);
            }
        });
        jPanel1.add(sup_writeFile);
        sup_writeFile.setBounds(60, 440, 170, 70);

        sup_show.setBackground(new java.awt.Color(79, 240, 170));
        sup_show.setFont(new java.awt.Font("Andika", 0, 14)); // NOI18N
        sup_show.setForeground(new java.awt.Color(1, 31, 106));
        sup_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abscorp/images/eye_1.png"))); // NOI18N
        sup_show.setText("Show");
        sup_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sup_showActionPerformed(evt);
            }
        });
        jPanel1.add(sup_show);
        sup_show.setBounds(250, 370, 140, 40);

        txt_area.setBackground(new java.awt.Color(255, 217, 180));
        txt_area.setColumns(20);
        txt_area.setFont(new java.awt.Font("Andika", 1, 16)); // NOI18N
        txt_area.setForeground(new java.awt.Color(1, 1, 1));
        txt_area.setRows(10);
        txt_area.setText("type here ...");
        txt_area.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ver_scrl.setViewportView(txt_area);

        jPanel1.add(ver_scrl);
        ver_scrl.setBounds(490, 270, 400, 270);

        btn_save.setBackground(new java.awt.Color(79, 240, 170));
        btn_save.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        btn_save.setForeground(new java.awt.Color(1, 31, 106));
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abscorp/images/save.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save);
        btn_save.setBounds(770, 550, 120, 40);

        jLabel1.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(132, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abscorp/images/bakb.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-1, -2, 910, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed

        loign x = new loign();
        x.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void sup_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sup_comboActionPerformed


      
        // TODO add your handling code here:
    }//GEN-LAST:event_sup_comboActionPerformed

    private void sup_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sup_showActionPerformed

        
        try{
            
            empID.setVisible(true);
            firstName.setVisible(true);
            lastName.setVisible(true);
            age.setVisible(true);
            dob.setVisible(true);
            email.setVisible(true);
            contact.setVisible(true);
            sup_status.setVisible(true);
            salary.setVisible(true);
            
            sup_firstName.setVisible(true);
            sup_empID.setVisible(true);
            sup_lastName.setVisible(true);
            sup_age.setVisible(true);
            sup_dob.setVisible(true);
            sup_contact.setVisible(true);
            sup_email.setVisible(true);
            sup_salary.setVisible(true);
            
            btn_save.setVisible(false);
            txt_area.setVisible(false);
            ver_scrl.setVisible(false);
        
        
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(null, "Error in unhiding details");
        }
        
        
        
        
        try{
           
            String employee = sup_combo.getSelectedItem().toString();
        String sql = "SELECT * FROM employee WHERE empId+ ' , '+firstName = ?";
        pst = conn.prepareStatement(sql);
        pst.setString(1,employee);
        rs = pst.executeQuery();
        
        while(rs.next()){
            String empID = rs.getString(1);
            sup_empID.setText(empID);
            
            String salary = rs.getString(4);
            sup_salary.setText(salary);
            
            String firstName = rs.getString(6);
            sup_firstName.setText(firstName);
            
            String lastName = rs.getString(7);
            sup_lastName.setText(lastName);
            
            String age = rs.getString(8);
            sup_age.setText(age);
            
            String dob = rs.getString(10);
            sup_dob.setText(dob);
            
            String email = rs.getString(11);
            sup_email.setText(email);
            
            String contact = rs.getString(12);
            sup_contact.setText(contact);
            
            String status = rs.getString(13);
            sup_status.setText(status);
            
            
            if ("dismissed".equals(status)){
                sup_delete.setVisible(true);
            }else{
                sup_delete.setVisible(false);
            }
            
        }
    
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error of retriving data of employee from database");
        JOptionPane.showMessageDialog(null,e);
        
    }



        // TODO add your handling code here:
    }//GEN-LAST:event_sup_showActionPerformed

    private void sup_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sup_deleteActionPerformed
 
        try{
            
        String employee = sup_empID.getText() + " , " + sup_firstName.getText();
        sup_combo.removeItem(employee);
        
        
        String sql = "DELETE FROM employee WHERE empId = ?";
        pst = conn.prepareStatement(sql);
        String ID = sup_empID.getText();
        pst.setString(1,ID);
        pst.execute();
        
        
        
        hideAll();
        
         JOptionPane.showMessageDialog(null,"Successfully deleted the record");
        
            
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"delete action not performed");
        JOptionPane.showMessageDialog(null,e);
        
    }
     

        // TODO add your handling code here:
    }//GEN-LAST:event_sup_deleteActionPerformed

    private void sup_writeFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sup_writeFileActionPerformed
        
        
        btn_save.setVisible(true);
        txt_area.setVisible(true);
        ver_scrl.setVisible(true);
        
        txt_area.setText("type here ...");



        // TODO add your handling code here:
    }//GEN-LAST:event_sup_writeFileActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

        btn_save.setVisible(false);
        txt_area.setVisible(false);
        ver_scrl.setVisible(false);
        String data = txt_area.getText();
        
            
        
        int returnValue = saveFileChooser.showSaveDialog(this);
        
        if(returnValue == JFileChooser.APPROVE_OPTION){
            
            try{
                
                
                File outputFile = saveFileChooser.getSelectedFile();
                PrintWriter output = new PrintWriter(outputFile);
                
                output.write(data);
                
                output.flush();
                
                output.close();
                
                JOptionPane.showMessageDialog(null, "Saved Successfully ");
                
            
            
            }catch (IOException ioe){
                
                JOptionPane.showMessageDialog(null, ioe);
            }
            
            
        }else{
            JOptionPane.showMessageDialog(null, "No file choosen ");
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supervisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel email;
    private javax.swing.JLabel empID;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_username;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel salary;
    private javax.swing.JLabel sup_age;
    private javax.swing.JComboBox<String> sup_combo;
    private javax.swing.JLabel sup_contact;
    private javax.swing.JButton sup_delete;
    private javax.swing.JLabel sup_dob;
    private javax.swing.JLabel sup_email;
    private javax.swing.JLabel sup_empID;
    private javax.swing.JLabel sup_firstName;
    private javax.swing.JLabel sup_lastName;
    private javax.swing.JLabel sup_salary;
    private javax.swing.JButton sup_show;
    private javax.swing.JLabel sup_status;
    private javax.swing.JButton sup_writeFile;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JScrollPane ver_scrl;
    // End of variables declaration//GEN-END:variables
}
