/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abscorp;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author muzammil
 */
public class associateUpdate extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form associateUpdate
     */
    public associateUpdate() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        label_username.setText((Employee.username).toString());
        
        conn = db.java_db();
        
        
         try{
          String sql= "select * from employee where username = ? ";

            pst = conn.prepareStatement(sql);
          
            pst.setString(1, Employee.username);
            

            rs = pst.executeQuery();
            
             while(rs.next()){
            
            
            
            String firstName = rs.getString(6);
            txt_firstName.setText(firstName);
            
          //  JOptionPane.showMessageDialog(null, "now here");
            
            String lastName = rs.getString(7);
            txt_lastName.setText(lastName);
            
            String contact = rs.getString(12);
            txt_contact.setText(contact);
            
            String email = rs.getString(11);
            txt_email.setText(email);
            
            String age = rs.getString(8);
            txt_age.setText(age);
            
            String dob = rs.getString(10);
            txt_dob.setText(dob);
            


            
            
             }
            
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
    }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        radio_male = new javax.swing.JRadioButton();
        radio_female = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        txt_firstName = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(179, 254, 157));
        jLabel2.setText("Logged as  :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 550, 110, 30);

        label_username.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        label_username.setForeground(new java.awt.Color(179, 254, 157));
        label_username.setText("username");
        jPanel1.add(label_username);
        label_username.setBounds(130, 540, 150, 50);

        btn_back.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        btn_back.setForeground(new java.awt.Color(37, 46, 164));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abscorp/images/goback.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(10, 10, 150, 50);

        jLabel3.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("First Name  :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 50, 140, 40);

        jLabel4.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Surname     :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 100, 120, 40);

        jLabel5.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Age              :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 140, 130, 50);

        jLabel6.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Gender        :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 190, 140, 50);

        radio_male.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        radio_male.setForeground(new java.awt.Color(254, 254, 254));
        radio_male.setText("Male");
        radio_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_maleActionPerformed(evt);
            }
        });
        jPanel1.add(radio_male);
        radio_male.setBounds(340, 200, 100, 40);

        radio_female.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        radio_female.setForeground(new java.awt.Color(254, 254, 254));
        radio_female.setText("Female");
        radio_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_femaleActionPerformed(evt);
            }
        });
        jPanel1.add(radio_female);
        radio_female.setBounds(430, 200, 100, 40);

        jLabel7.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("D.O.B           :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 240, 130, 40);

        jLabel8.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Contact       :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(200, 280, 140, 50);

        jLabel9.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("E-mail          :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 330, 110, 40);

        btn_update.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        btn_update.setForeground(new java.awt.Color(11, 0, 210));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abscorp/images/update.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update);
        btn_update.setBounds(650, 460, 160, 40);

        txt_firstName.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        txt_firstName.setForeground(new java.awt.Color(58, 139, 57));
        txt_firstName.setText("Muzammil");
        jPanel1.add(txt_firstName);
        txt_firstName.setBounds(330, 50, 200, 40);

        txt_lastName.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        txt_lastName.setForeground(new java.awt.Color(58, 139, 57));
        txt_lastName.setText("Thottathil");
        jPanel1.add(txt_lastName);
        txt_lastName.setBounds(330, 100, 200, 40);

        txt_age.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        txt_age.setForeground(new java.awt.Color(58, 139, 57));
        txt_age.setText("21");
        jPanel1.add(txt_age);
        txt_age.setBounds(330, 150, 200, 40);

        txt_dob.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        txt_dob.setForeground(new java.awt.Color(58, 139, 57));
        txt_dob.setText("13/10/1998");
        txt_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dobActionPerformed(evt);
            }
        });
        jPanel1.add(txt_dob);
        txt_dob.setBounds(330, 240, 200, 40);

        txt_contact.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        txt_contact.setForeground(new java.awt.Color(58, 139, 57));
        txt_contact.setText("9746404624");
        jPanel1.add(txt_contact);
        txt_contact.setBounds(330, 290, 200, 40);

        txt_email.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        txt_email.setForeground(new java.awt.Color(58, 139, 57));
        txt_email.setText("muzammilthottathil@cet.ac.in");
        jPanel1.add(txt_email);
        txt_email.setBounds(330, 340, 360, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abscorp/images/bakb.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dobActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed

        Associate x = new Associate();
        x.setVisible(true);
        this.dispose();



        // TODO add your handling code here:
    }//GEN-LAST:event_btn_backActionPerformed

    private void radio_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_maleActionPerformed

        gender = "male";
        radio_male.setSelected(true);
        radio_female.setSelected(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_radio_maleActionPerformed

    private void radio_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_femaleActionPerformed

        gender = "female";
        radio_female.setSelected(true);
        radio_male.setSelected(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_femaleActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed

        String sql= "UPDATE employee SET dob = ?,age = ?,firstName =?,lastName=?,contact=?,email=?,gender=? WHERE username = ?";
        try{

            pst = conn.prepareStatement(sql);
            
            pst.setString(1, txt_dob.getText());
            pst.setString(2, txt_age.getText());
            pst.setString(3, txt_firstName.getText());
            pst.setString(4, txt_lastName.getText());
            pst.setString(5, txt_contact.getText());
            pst.setString(6, txt_email.getText());
            pst.setString(7, gender);
            pst.setString(8, Employee.username);
          
            
           pst.execute();
           JOptionPane.showMessageDialog(null, "Updated Successfully");
            
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                
                rs.close();
                pst.close();
                
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
        
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(associateUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(associateUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(associateUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(associateUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new associateUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_username;
    private javax.swing.JRadioButton radio_female;
    private javax.swing.JRadioButton radio_male;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    // End of variables declaration//GEN-END:variables

private String gender;

}
