/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abscorp;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author muzammil
 */
public class Associate extends javax.swing.JFrame {
    
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Associate
     */
    public Associate() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        
        label_username.setText((Employee.username).toString());
        
        
        conn = db.java_db();
       //////////////////////////////////////////////// 
        
        
        try{
          String sql= "select * from employee where username = ? ";

            pst = conn.prepareStatement(sql);
          
            pst.setString(1, Employee.username);
            

            rs = pst.executeQuery();
            
             while(rs.next()){
            
            String empID = rs.getString(1);
            dis_empID.setText((empID));
            
            String firstName = rs.getString(6);
            dis_firstName.setText(firstName);
            
          //  JOptionPane.showMessageDialog(null, "now here");
            
            String lastName = rs.getString(7);
            dis_lastName.setText(lastName);
            
            String contact = rs.getString(12);
            dis_contact.setText(contact);
            
            String email = rs.getString(11);
            dis_email.setText(email);
            
            String age = rs.getString(8);
            dis_age.setText(age);
            
            String dob = rs.getString(10);
            dis_dob.setText(dob);
            
            String gender = rs.getString(9);
            dis_gender.setText(gender);
            
            String salary = rs.getString(4);
            dis_salary.setText(salary);
            
            
             }
            
            
            
        
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                
                rs.close();
                pst.close();
                
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
        
        }
        
        //////////////////////////////////////////////////////////
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dis_empID = new javax.swing.JLabel();
        dis_firstName = new javax.swing.JLabel();
        dis_lastName = new javax.swing.JLabel();
        dis_gender = new javax.swing.JLabel();
        dis_dob = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dis_age = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dis_contact = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dis_email = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dis_salary = new javax.swing.JLabel();
        dis_btn_update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(131, 254, 116));
        jLabel1.setText("Logged as  :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 550, 100, 40);

        label_username.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        label_username.setForeground(new java.awt.Color(131, 254, 116));
        label_username.setText("username");
        jPanel1.add(label_username);
        label_username.setBounds(130, 550, 130, 40);

        btn_logout.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        btn_logout.setFont(new java.awt.Font("Andika", 0, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(161, 20, 48));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abscorp/images/powee.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout);
        btn_logout.setBounds(760, 20, 140, 50);

        jLabel3.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("First Name     :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 80, 130, 30);

        jLabel4.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Surname        :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 120, 130, 40);

        jLabel5.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Employee ID  :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 30, 130, 40);

        jLabel6.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Gender          :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 170, 130, 30);

        jLabel7.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("D.O.B             :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 210, 130, 40);

        dis_empID.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        dis_empID.setForeground(new java.awt.Color(254, 254, 254));
        dis_empID.setText("id");
        jPanel1.add(dis_empID);
        dis_empID.setBounds(210, 30, 110, 40);

        dis_firstName.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        dis_firstName.setForeground(new java.awt.Color(254, 254, 254));
        dis_firstName.setText("Muz");
        jPanel1.add(dis_firstName);
        dis_firstName.setBounds(210, 80, 150, 30);

        dis_lastName.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        dis_lastName.setForeground(new java.awt.Color(248, 248, 248));
        dis_lastName.setText("muz");
        jPanel1.add(dis_lastName);
        dis_lastName.setBounds(210, 120, 190, 40);

        dis_gender.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        dis_gender.setForeground(new java.awt.Color(254, 254, 254));
        dis_gender.setText("Male");
        jPanel1.add(dis_gender);
        dis_gender.setBounds(210, 160, 170, 50);

        dis_dob.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        dis_dob.setForeground(new java.awt.Color(254, 254, 254));
        dis_dob.setText("13/10/1998");
        jPanel1.add(dis_dob);
        dis_dob.setBounds(210, 210, 130, 40);

        jLabel13.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(254, 254, 254));
        jLabel13.setText("Age                 :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 260, 130, 40);

        dis_age.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        dis_age.setForeground(new java.awt.Color(254, 254, 254));
        dis_age.setText("21");
        jPanel1.add(dis_age);
        dis_age.setBounds(210, 250, 340, 60);

        jLabel15.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(254, 254, 254));
        jLabel15.setText("Conatct          :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(70, 310, 130, 40);

        dis_contact.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        dis_contact.setForeground(new java.awt.Color(254, 254, 254));
        dis_contact.setText("9746404624");
        jPanel1.add(dis_contact);
        dis_contact.setBounds(210, 310, 250, 40);

        jLabel8.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("E-mail             :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 360, 130, 40);

        dis_email.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        dis_email.setForeground(new java.awt.Color(254, 254, 254));
        dis_email.setText("muzammilthottathil@cet.ac.in");
        jPanel1.add(dis_email);
        dis_email.setBounds(210, 350, 310, 60);

        jLabel10.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("Basic Salary   :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 400, 140, 60);

        dis_salary.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        dis_salary.setForeground(new java.awt.Color(254, 254, 254));
        dis_salary.setText("52000");
        jPanel1.add(dis_salary);
        dis_salary.setBounds(210, 400, 260, 60);

        dis_btn_update.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        dis_btn_update.setForeground(new java.awt.Color(0, 33, 214));
        dis_btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abscorp/images/update.png"))); // NOI18N
        dis_btn_update.setText("Update");
        dis_btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dis_btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(dis_btn_update);
        dis_btn_update.setBounds(370, 490, 180, 40);

        jLabel2.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abscorp/images/bakb.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 910, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed

        loign x = new loign();
        x.setVisible(true);
        this.dispose();



        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void dis_btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dis_btn_updateActionPerformed
        // TODO add your handling code here:
        associateUpdate x = new associateUpdate();
        x.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_dis_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Associate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Associate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Associate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Associate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Associate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel dis_age;
    private javax.swing.JButton dis_btn_update;
    private javax.swing.JLabel dis_contact;
    private javax.swing.JLabel dis_dob;
    private javax.swing.JLabel dis_email;
    private javax.swing.JLabel dis_empID;
    private javax.swing.JLabel dis_firstName;
    private javax.swing.JLabel dis_gender;
    private javax.swing.JLabel dis_lastName;
    private javax.swing.JLabel dis_salary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_username;
    // End of variables declaration//GEN-END:variables
}





/*
String sql= "UPDATE employee SET dob = '13/10/1998',age = '21' WHERE (`username` = 'taqnar1')";
        try{

            pst = conn.prepareStatement(sql);
            
            pst.setString(1, txt_username.getText());
            pst.setString(2, txt_password.getText());
            pst.setString(3, txt_combo.getSelectedItem().toString());
          
            
           pst.execute();
            
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                
                rs.close();
                pst.close();
                
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
        
        }
*/